### ISSUE TITLE
Discovery inside docker

### ISSUE THREAD

**Issue by ngalaiko** [ngalayko/p2p#9]
Make sure that peers can discover each other while started via the dispatcher.

**Comment by ngalayko** [comment]
Docker Swarm default network driver doesn't support UDP multicast. Instead will use consul catalog for both service discovery and traefik routes. https://docs.traefik.io/configuration/backends/consulcatalog/

**Comment by ngalaiko** [comment]
#12

consul catalog used as a discovery. 
this also changes traefik provider to consul catalog from consul KV storage.
